Lego control+ image
B-AROL-O/ARNEIS pull request #296
Opened 2022-04-05 11:40 UTC by davmacario

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2022-04-05 16:20 UTC, gmacario requested changes
Please create a page `/docs/howto/howto-xxxx.md` (choose `xxxxx` based on the actual contents of the page) which includes this image and describes:

1. What this program is supposed to do
2. Which are the prerequisites (i.e. which motors have to be connected where)
3. Shows how it works in practice
4. etc.

2022-04-06 07:14 UTC, davmacario commented
As I was going to update the documentation I realized I don't remember precisely where the motors are attached, but since I'm isolated in my room due to covid reasons I am not able to look at the prototype of the conveyor belt and cannot find any images of the final prototype (the one which appeared in the video-presentation) in thee ARNEIS repo...

2022-04-07 10:24 UTC, gmacario commented
> I am not able to look at the prototype of the conveyor belt and cannot find any images of the final prototype

You may always ask help from someone else who knows this information, such as @filmacario

2022-05-08 13:17 UTC, gmacario commented
Merging as-is, will deal with HOWTO page creating in a future PR

2022-05-08 13:17 UTC, gmacario approved these changes

2022-05-08 13:17 UTC, merged